[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "numpy>=2.3.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "werkzeug>=3.1.3",
]
